Add author and i18n
Osis-Uclouvain/osis-history pull request #14
Opened 2021-05-06 09:54 UTC by SebCorbin

2021-05-06 09:58 UTC, albrugnetti approved these changes

2021-05-06 13:55 UTC, AL9000 commented on frontend/components/Table.vue
> +      <td colspan="3">No history entry yet.</td>
`{{ $t('No history entry yet.') }}` ?

2021-05-06 13:55 UTC, AL9000 commented on frontend/components/Table.vue
> +    <tbody v-if="entries.length">
`v-if="entries && entries.length"` ?

2021-05-06 14:14 UTC, SebCorbin commented on frontend/components/Table.vue
> +    <tbody v-if="entries.length">
`entries` étant une prop, elle est requise et le fonctionnement ne sera pas monté si elle n'est pas présente

2021-05-06 14:15 UTC, SebCorbin commented on frontend/components/Table.vue
> +      <td colspan="3">No history entry yet.</td>
👍

2021-05-06 14:27 UTC, AL9000 approved these changes

2021-05-07 09:16 UTC, albrugnetti requested changes

2021-05-07 09:16 UTC, albrugnetti commented on frontend/components/Timeline.vue
> +              {{ new Date(entry.created).toLocaleString() }}
Est-ce que ça ne doit pas être la responsabilité de l'API de renvoyer le format en adéquation avec la langue souhaitée ?
Evite d'avoir une différence entre la langue choisie par l'utilisateur et la langue du navigateur

2021-05-07 09:16 UTC, albrugnetti commented on utilities.py
> +def get_history_entries(object_uuid: Union[str, UUID]) -> List[Tuple[datetime, str, str]]:
Est-ce qu'on ne peut pas utiliser les nametuples (https://docs.python.org/fr/3/library/collections.html#collections.namedtuple) afin d'avoir quelques choses de plus explicites.
History = namedtuple('History ', ['created', 'message', 'author'])

2021-05-07 09:52 UTC, SebCorbin commented on utilities.py
> +def get_history_entries(object_uuid: Union[str, UUID]) -> List[Tuple[datetime, str, str]]:
J'ai mis ça en place mais pour plus tard, quand on va intégrer `message_fr` et `message_en`, on doit renvoyer les deux ?

2021-05-07 09:53 UTC, SebCorbin commented on frontend/components/Timeline.vue
> +              {{ new Date(entry.created).toLocaleString() }}
👍

2021-05-07 10:14 UTC, albrugnetti commented on utilities.py
> +def get_history_entries(object_uuid: Union[str, UUID]) -> List[Tuple[datetime, str, str]]:
Cet utilitaire peut soit : 

- Avoir un paramètre supplémentaire (language)
- Retourner les deux 

Qu'est ce qui sera plus facile à l'utilisation ? Je vous laisse faire le choix

2021-05-10 06:03 UTC, merged