[OSIS-9086] Add styles for osis-history
Osis-Uclouvain/osis-history pull request #37
Opened 2024-06-04 15:03 UTC by leboiss

2024-06-05 08:15 UTC, mdartic approved these changes

2024-06-05 08:18 UTC, mdartic requested changes

2024-06-05 08:18 UTC, mdartic commented on frontend/HistoryViewer.vue
> +}
Alors, pas sûr que ça va fonctionner, car ce style risque de déborder sur les autres fichiers.

Tu dois les préfixer de `.history-viewer` tel que c'est écrit, comme pour `.viewport` et `.spinner`.

Il serait à mon avis tout à fait possible de faire du nested css, mais je ne connais pas la conf de ce projet vue.

Les styles ne sont pas `scoped` sur ce fichier, ça veut dire que si tu écris une règle comme `.btn-default`, tous les boutons qui auront cette classe, du module `osis-history` ou non, se verront appliquer ce style. C'est très dangereux.

@mathieuzen est ce que tu penses qu'on pourrait "scoper" les styles de ce composant ?

2024-06-05 08:31 UTC, mathieuzen commented on frontend/HistoryViewer.vue
> +}
Si par "scoper" on entend préfixer avec .history-viewer ici, ça me convient oui et ça évitera d'avoir une sorte de "fuite de style"

2024-06-05 08:35 UTC, mdartic commented on frontend/HistoryViewer.vue
> +}
alors, y'avait 2 remarques dans mon commentaire :-) désolé, c'est pas clair

on peut préfixer avec `.history-viewer`, ok avec toi, et c'est indispensable.

l'autre question concernait l'usage de cette syntaxe : 

```vue
<style scoped>
.example {
  color: red;
}
</style>

<template>
  <div class="example">hi</div>
</template>
```

qui a l'intérêt majeur de "scoper" les styles écrits au seules instances de ce composant Vue. (par la création automagique d'un data attribute unique aux instances de ce composant)

Je ne sais pas si c'est une syntaxe que vous avez déjà utilisé, que vous préconisez, ou pas, mais je soulevais le point ici car j'ai remarqué qu'il n'y avait pas l'attribut `scoped` au niveau de la déclaration des styles (et c'est plutôt une bonne pratique de scoper ses styles).

2024-06-05 11:03 UTC, leboiss commented
@mathieuzen  j'ai rajouté la class .history-viewer pour éviter les effets de bords

2024-06-07 08:03 UTC, mdartic approved these changes

2024-06-07 09:33 UTC, mathieuzen commented on frontend/HistoryViewer.vue
> +}
Ok je comprends mieux. C'est un peu ma faute aussi car j'avais pas ouvert l'url. Oui, pour nous, toute bonne pratique qui vise à éviter des soucis futurs est bonne à prendre.

2024-06-07 09:35 UTC, mathieuzen reviewed
On peut essayer d'ajouter le` <style scoped>` ici alors pour commencer ?

2024-06-07 09:56 UTC, mdartic commented
Ça se tente, j'ai regardé le template, il y a des sous composants mais ils ne sont pas impactés par les styles définis dans ce fichier. (s'il y en avait eu, on aurait pu utiliser le sélecteur [`:deep`](https://vuejs.org/api/sfc-css-features.html#deep-selectors))
@leboiss désolé, est ce que tu peux modifier la zone de style en : 
* rajoutant l'attribut `scoped`, soit `<style scoped>`
* supprimer la classe `.history-viewer` de tes sélecteurs, il ne devrait plus être utile désormais en scopé
* regénérer le `.css`

2024-06-10 08:43 UTC, leboiss commented on frontend/HistoryViewer.vue
> +}
@mathieuzen @mdartic  le scope pour les styles et en place

2024-06-27 07:46 UTC, mathieuzen approved these changes

2024-06-27 07:46 UTC, merged